name: Medicard
on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x 
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build 'Medicard.Tests/Medicard.Tests.csproj' --configuration Release
    - name: Test
      run: dotnet test 'Medicard.Tests/Medicard.Tests.csproj' --no-restore --configuration Release
